# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wafer_filter_settings.ui'
#
# Created: Mon Oct  9 17:13:40 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Wafer_Filter_Settings(object):
    def setupUi(self, Wafer_Filter_Settings):
        Wafer_Filter_Settings.setObjectName("Wafer_Filter_Settings")
        Wafer_Filter_Settings.resize(1634, 210)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Wafer_Filter_Settings.sizePolicy().hasHeightForWidth())
        Wafer_Filter_Settings.setSizePolicy(sizePolicy)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(Wafer_Filter_Settings)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.wafer_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.wafer_label.setFont(font)
        self.wafer_label.setObjectName("wafer_label")
        self.verticalLayout_8.addWidget(self.wafer_label)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Idmax_min_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Idmax_min_label.sizePolicy().hasHeightForWidth())
        self.Idmax_min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Idmax_min_label.setFont(font)
        self.Idmax_min_label.setObjectName("Idmax_min_label")
        self.horizontalLayout.addWidget(self.Idmax_min_label)
        self.min_Idmax_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.min_Idmax_but.setFont(font)
        self.min_Idmax_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.min_Idmax_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.min_Idmax_but.setCheckable(True)
        self.min_Idmax_but.setChecked(False)
        self.min_Idmax_but.setObjectName("min_Idmax_but")
        self.horizontalLayout.addWidget(self.min_Idmax_but)
        self.Idmax_min_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Idmax_min_selector.setFont(font)
        self.Idmax_min_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Idmax_min_selector.setReadOnly(False)
        self.Idmax_min_selector.setObjectName("Idmax_min_selector")
        self.horizontalLayout.addWidget(self.Idmax_min_selector)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Idmax_max_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Idmax_max_label.sizePolicy().hasHeightForWidth())
        self.Idmax_max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Idmax_max_label.setFont(font)
        self.Idmax_max_label.setObjectName("Idmax_max_label")
        self.horizontalLayout_2.addWidget(self.Idmax_max_label)
        self.max_Idmax_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.max_Idmax_but.setFont(font)
        self.max_Idmax_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.max_Idmax_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.max_Idmax_but.setCheckable(True)
        self.max_Idmax_but.setChecked(False)
        self.max_Idmax_but.setObjectName("max_Idmax_but")
        self.horizontalLayout_2.addWidget(self.max_Idmax_but)
        self.Idmax_max_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Idmax_max_selector.setFont(font)
        self.Idmax_max_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Idmax_max_selector.setReadOnly(False)
        self.Idmax_max_selector.setObjectName("Idmax_max_selector")
        self.horizontalLayout_2.addWidget(self.Idmax_max_selector)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_9.addLayout(self.verticalLayout)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.IdmaxFOC_min_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IdmaxFOC_min_label.sizePolicy().hasHeightForWidth())
        self.IdmaxFOC_min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.IdmaxFOC_min_label.setFont(font)
        self.IdmaxFOC_min_label.setObjectName("IdmaxFOC_min_label")
        self.horizontalLayout_17.addWidget(self.IdmaxFOC_min_label)
        self.min_IdmaxFOC_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.min_IdmaxFOC_but.setFont(font)
        self.min_IdmaxFOC_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.min_IdmaxFOC_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.min_IdmaxFOC_but.setCheckable(True)
        self.min_IdmaxFOC_but.setChecked(False)
        self.min_IdmaxFOC_but.setObjectName("min_IdmaxFOC_but")
        self.horizontalLayout_17.addWidget(self.min_IdmaxFOC_but)
        self.IdmaxFOC_min_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.IdmaxFOC_min_selector.setFont(font)
        self.IdmaxFOC_min_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.IdmaxFOC_min_selector.setReadOnly(False)
        self.IdmaxFOC_min_selector.setObjectName("IdmaxFOC_min_selector")
        self.horizontalLayout_17.addWidget(self.IdmaxFOC_min_selector)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.IdmaxFOC_max_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.IdmaxFOC_max_label.sizePolicy().hasHeightForWidth())
        self.IdmaxFOC_max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.IdmaxFOC_max_label.setFont(font)
        self.IdmaxFOC_max_label.setObjectName("IdmaxFOC_max_label")
        self.horizontalLayout_18.addWidget(self.IdmaxFOC_max_label)
        self.max_IdmaxFOC_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.max_IdmaxFOC_but.setFont(font)
        self.max_IdmaxFOC_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.max_IdmaxFOC_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.max_IdmaxFOC_but.setCheckable(True)
        self.max_IdmaxFOC_but.setChecked(False)
        self.max_IdmaxFOC_but.setObjectName("max_IdmaxFOC_but")
        self.horizontalLayout_18.addWidget(self.max_IdmaxFOC_but)
        self.IdmaxFOC_max_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.IdmaxFOC_max_selector.setFont(font)
        self.IdmaxFOC_max_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.IdmaxFOC_max_selector.setReadOnly(False)
        self.IdmaxFOC_max_selector.setObjectName("IdmaxFOC_max_selector")
        self.horizontalLayout_18.addWidget(self.IdmaxFOC_max_selector)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_9.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.onoffratio_min_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onoffratio_min_label.sizePolicy().hasHeightForWidth())
        self.onoffratio_min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.onoffratio_min_label.setFont(font)
        self.onoffratio_min_label.setObjectName("onoffratio_min_label")
        self.horizontalLayout_3.addWidget(self.onoffratio_min_label)
        self.min_onoffratio_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.min_onoffratio_but.setFont(font)
        self.min_onoffratio_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.min_onoffratio_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.min_onoffratio_but.setCheckable(True)
        self.min_onoffratio_but.setChecked(False)
        self.min_onoffratio_but.setObjectName("min_onoffratio_but")
        self.horizontalLayout_3.addWidget(self.min_onoffratio_but)
        self.onoffratio_min_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.onoffratio_min_selector.setFont(font)
        self.onoffratio_min_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.onoffratio_min_selector.setReadOnly(False)
        self.onoffratio_min_selector.setObjectName("onoffratio_min_selector")
        self.horizontalLayout_3.addWidget(self.onoffratio_min_selector)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.onoffratio_max_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.onoffratio_max_label.sizePolicy().hasHeightForWidth())
        self.onoffratio_max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.onoffratio_max_label.setFont(font)
        self.onoffratio_max_label.setObjectName("onoffratio_max_label")
        self.horizontalLayout_4.addWidget(self.onoffratio_max_label)
        self.max_onoffratio_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.max_onoffratio_but.setFont(font)
        self.max_onoffratio_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.max_onoffratio_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.max_onoffratio_but.setCheckable(True)
        self.max_onoffratio_but.setChecked(False)
        self.max_onoffratio_but.setObjectName("max_onoffratio_but")
        self.horizontalLayout_4.addWidget(self.max_onoffratio_but)
        self.onoffratio_max_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.onoffratio_max_selector.setFont(font)
        self.onoffratio_max_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.onoffratio_max_selector.setReadOnly(False)
        self.onoffratio_max_selector.setObjectName("onoffratio_max_selector")
        self.horizontalLayout_4.addWidget(self.onoffratio_max_selector)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_9.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.TLM_Rc_min_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TLM_Rc_min_label.sizePolicy().hasHeightForWidth())
        self.TLM_Rc_min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rc_min_label.setFont(font)
        self.TLM_Rc_min_label.setObjectName("TLM_Rc_min_label")
        self.horizontalLayout_10.addWidget(self.TLM_Rc_min_label)
        self.TLM_Rc_min_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rc_min_but.setFont(font)
        self.TLM_Rc_min_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TLM_Rc_min_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.TLM_Rc_min_but.setCheckable(True)
        self.TLM_Rc_min_but.setChecked(False)
        self.TLM_Rc_min_but.setObjectName("TLM_Rc_min_but")
        self.horizontalLayout_10.addWidget(self.TLM_Rc_min_but)
        self.TLM_Rc_min_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rc_min_selector.setFont(font)
        self.TLM_Rc_min_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.TLM_Rc_min_selector.setReadOnly(False)
        self.TLM_Rc_min_selector.setObjectName("TLM_Rc_min_selector")
        self.horizontalLayout_10.addWidget(self.TLM_Rc_min_selector)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.TLM_Rc_max_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TLM_Rc_max_label.sizePolicy().hasHeightForWidth())
        self.TLM_Rc_max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rc_max_label.setFont(font)
        self.TLM_Rc_max_label.setObjectName("TLM_Rc_max_label")
        self.horizontalLayout_11.addWidget(self.TLM_Rc_max_label)
        self.TLM_Rc_max_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rc_max_but.setFont(font)
        self.TLM_Rc_max_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TLM_Rc_max_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.TLM_Rc_max_but.setCheckable(True)
        self.TLM_Rc_max_but.setChecked(False)
        self.TLM_Rc_max_but.setObjectName("TLM_Rc_max_but")
        self.horizontalLayout_11.addWidget(self.TLM_Rc_max_but)
        self.TLM_Rc_max_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rc_max_selector.setFont(font)
        self.TLM_Rc_max_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.TLM_Rc_max_selector.setReadOnly(False)
        self.TLM_Rc_max_selector.setObjectName("TLM_Rc_max_selector")
        self.horizontalLayout_11.addWidget(self.TLM_Rc_max_selector)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.TLM_Rsh_min_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TLM_Rsh_min_label.sizePolicy().hasHeightForWidth())
        self.TLM_Rsh_min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rsh_min_label.setFont(font)
        self.TLM_Rsh_min_label.setObjectName("TLM_Rsh_min_label")
        self.horizontalLayout_12.addWidget(self.TLM_Rsh_min_label)
        self.TLM_Rsh_min_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rsh_min_but.setFont(font)
        self.TLM_Rsh_min_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TLM_Rsh_min_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.TLM_Rsh_min_but.setCheckable(True)
        self.TLM_Rsh_min_but.setChecked(False)
        self.TLM_Rsh_min_but.setObjectName("TLM_Rsh_min_but")
        self.horizontalLayout_12.addWidget(self.TLM_Rsh_min_but)
        self.TLM_Rsh_min_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rsh_min_selector.setFont(font)
        self.TLM_Rsh_min_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.TLM_Rsh_min_selector.setReadOnly(False)
        self.TLM_Rsh_min_selector.setObjectName("TLM_Rsh_min_selector")
        self.horizontalLayout_12.addWidget(self.TLM_Rsh_min_selector)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.TLM_Rsh_max_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TLM_Rsh_max_label.sizePolicy().hasHeightForWidth())
        self.TLM_Rsh_max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rsh_max_label.setFont(font)
        self.TLM_Rsh_max_label.setObjectName("TLM_Rsh_max_label")
        self.horizontalLayout_13.addWidget(self.TLM_Rsh_max_label)
        self.TLM_Rsh_max_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rsh_max_but.setFont(font)
        self.TLM_Rsh_max_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.TLM_Rsh_max_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.TLM_Rsh_max_but.setCheckable(True)
        self.TLM_Rsh_max_but.setChecked(False)
        self.TLM_Rsh_max_but.setObjectName("TLM_Rsh_max_but")
        self.horizontalLayout_13.addWidget(self.TLM_Rsh_max_but)
        self.TLM_Rsh_max_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TLM_Rsh_max_selector.setFont(font)
        self.TLM_Rsh_max_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.TLM_Rsh_max_selector.setReadOnly(False)
        self.TLM_Rsh_max_selector.setObjectName("TLM_Rsh_max_selector")
        self.horizontalLayout_13.addWidget(self.TLM_Rsh_max_selector)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9.addLayout(self.verticalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.Ronmin_min_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ronmin_min_label.sizePolicy().hasHeightForWidth())
        self.Ronmin_min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Ronmin_min_label.setFont(font)
        self.Ronmin_min_label.setObjectName("Ronmin_min_label")
        self.horizontalLayout_15.addWidget(self.Ronmin_min_label)
        self.Ronmin_min_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Ronmin_min_but.setFont(font)
        self.Ronmin_min_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Ronmin_min_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.Ronmin_min_but.setCheckable(True)
        self.Ronmin_min_but.setChecked(False)
        self.Ronmin_min_but.setObjectName("Ronmin_min_but")
        self.horizontalLayout_15.addWidget(self.Ronmin_min_but)
        self.Ronmin_min_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ronmin_min_selector.sizePolicy().hasHeightForWidth())
        self.Ronmin_min_selector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Ronmin_min_selector.setFont(font)
        self.Ronmin_min_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Ronmin_min_selector.setReadOnly(False)
        self.Ronmin_min_selector.setObjectName("Ronmin_min_selector")
        self.horizontalLayout_15.addWidget(self.Ronmin_min_selector)
        self.Igmax_min_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Igmax_min_label.sizePolicy().hasHeightForWidth())
        self.Igmax_min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Igmax_min_label.setFont(font)
        self.Igmax_min_label.setObjectName("Igmax_min_label")
        self.horizontalLayout_15.addWidget(self.Igmax_min_label)
        self.Igmax_min_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Igmax_min_but.setFont(font)
        self.Igmax_min_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Igmax_min_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.Igmax_min_but.setCheckable(True)
        self.Igmax_min_but.setChecked(False)
        self.Igmax_min_but.setObjectName("Igmax_min_but")
        self.horizontalLayout_15.addWidget(self.Igmax_min_but)
        self.Igmax_min_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Igmax_min_selector.sizePolicy().hasHeightForWidth())
        self.Igmax_min_selector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Igmax_min_selector.setFont(font)
        self.Igmax_min_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Igmax_min_selector.setReadOnly(False)
        self.Igmax_min_selector.setObjectName("Igmax_min_selector")
        self.horizontalLayout_15.addWidget(self.Igmax_min_selector)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.Ronmin_max_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ronmin_max_label.sizePolicy().hasHeightForWidth())
        self.Ronmin_max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Ronmin_max_label.setFont(font)
        self.Ronmin_max_label.setObjectName("Ronmin_max_label")
        self.horizontalLayout_16.addWidget(self.Ronmin_max_label)
        self.Ronmin_max_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ronmin_max_but.sizePolicy().hasHeightForWidth())
        self.Ronmin_max_but.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Ronmin_max_but.setFont(font)
        self.Ronmin_max_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Ronmin_max_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.Ronmin_max_but.setCheckable(True)
        self.Ronmin_max_but.setChecked(False)
        self.Ronmin_max_but.setObjectName("Ronmin_max_but")
        self.horizontalLayout_16.addWidget(self.Ronmin_max_but)
        self.Ronmin_max_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ronmin_max_selector.sizePolicy().hasHeightForWidth())
        self.Ronmin_max_selector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Ronmin_max_selector.setFont(font)
        self.Ronmin_max_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Ronmin_max_selector.setReadOnly(False)
        self.Ronmin_max_selector.setObjectName("Ronmin_max_selector")
        self.horizontalLayout_16.addWidget(self.Ronmin_max_selector)
        self.Igmax_max_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Igmax_max_label.sizePolicy().hasHeightForWidth())
        self.Igmax_max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Igmax_max_label.setFont(font)
        self.Igmax_max_label.setObjectName("Igmax_max_label")
        self.horizontalLayout_16.addWidget(self.Igmax_max_label)
        self.Igmax_max_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Igmax_max_but.setFont(font)
        self.Igmax_max_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.Igmax_max_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.Igmax_max_but.setCheckable(True)
        self.Igmax_max_but.setChecked(False)
        self.Igmax_max_but.setObjectName("Igmax_max_but")
        self.horizontalLayout_16.addWidget(self.Igmax_max_but)
        self.Igmax_max_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Igmax_max_selector.sizePolicy().hasHeightForWidth())
        self.Igmax_max_selector.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Igmax_max_selector.setFont(font)
        self.Igmax_max_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.Igmax_max_selector.setReadOnly(False)
        self.Igmax_max_selector.setObjectName("Igmax_max_selector")
        self.horizontalLayout_16.addWidget(self.Igmax_max_selector)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_14.addLayout(self.verticalLayout_6)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gmmax_min_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gmmax_min_label.sizePolicy().hasHeightForWidth())
        self.gmmax_min_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gmmax_min_label.setFont(font)
        self.gmmax_min_label.setObjectName("gmmax_min_label")
        self.horizontalLayout_5.addWidget(self.gmmax_min_label)
        self.min_gmmax_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.min_gmmax_but.setFont(font)
        self.min_gmmax_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.min_gmmax_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.min_gmmax_but.setCheckable(True)
        self.min_gmmax_but.setChecked(False)
        self.min_gmmax_but.setObjectName("min_gmmax_but")
        self.horizontalLayout_5.addWidget(self.min_gmmax_but)
        self.gmmax_min_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gmmax_min_selector.setFont(font)
        self.gmmax_min_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gmmax_min_selector.setReadOnly(False)
        self.gmmax_min_selector.setObjectName("gmmax_min_selector")
        self.horizontalLayout_5.addWidget(self.gmmax_min_selector)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gmmax_max_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gmmax_max_label.sizePolicy().hasHeightForWidth())
        self.gmmax_max_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gmmax_max_label.setFont(font)
        self.gmmax_max_label.setObjectName("gmmax_max_label")
        self.horizontalLayout_6.addWidget(self.gmmax_max_label)
        self.max_gmmax_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.max_gmmax_but.setFont(font)
        self.max_gmmax_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.max_gmmax_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.max_gmmax_but.setCheckable(True)
        self.max_gmmax_but.setChecked(False)
        self.max_gmmax_but.setObjectName("max_gmmax_but")
        self.horizontalLayout_6.addWidget(self.max_gmmax_but)
        self.gmmax_max_selector = QtWidgets.QLineEdit(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.gmmax_max_selector.setFont(font)
        self.gmmax_max_selector.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.gmmax_max_selector.setReadOnly(False)
        self.gmmax_max_selector.setObjectName("gmmax_max_selector")
        self.horizontalLayout_6.addWidget(self.gmmax_max_selector)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_14.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_8.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.filter_gate_compliance_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.filter_gate_compliance_but.setFont(font)
        self.filter_gate_compliance_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.filter_gate_compliance_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.filter_gate_compliance_but.setCheckable(True)
        self.filter_gate_compliance_but.setChecked(False)
        self.filter_gate_compliance_but.setAutoDefault(True)
        self.filter_gate_compliance_but.setDefault(False)
        self.filter_gate_compliance_but.setObjectName("filter_gate_compliance_but")
        self.horizontalLayout_7.addWidget(self.filter_gate_compliance_but)
        self.filter_gatecompliance_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_gatecompliance_label.sizePolicy().hasHeightForWidth())
        self.filter_gatecompliance_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.filter_gatecompliance_label.setFont(font)
        self.filter_gatecompliance_label.setObjectName("filter_gatecompliance_label")
        self.horizontalLayout_7.addWidget(self.filter_gatecompliance_label)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.filter_drain_compliance_but = QtWidgets.QPushButton(Wafer_Filter_Settings)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.filter_drain_compliance_but.setFont(font)
        self.filter_drain_compliance_but.setFocusPolicy(QtCore.Qt.NoFocus)
        self.filter_drain_compliance_but.setStyleSheet("background-color: hsv(0, 120, 255);\n"
"color: rgb(0, 0,0);")
        self.filter_drain_compliance_but.setCheckable(True)
        self.filter_drain_compliance_but.setChecked(False)
        self.filter_drain_compliance_but.setAutoDefault(True)
        self.filter_drain_compliance_but.setDefault(False)
        self.filter_drain_compliance_but.setObjectName("filter_drain_compliance_but")
        self.horizontalLayout_8.addWidget(self.filter_drain_compliance_but)
        self.filter_draincompliance_label = QtWidgets.QLabel(Wafer_Filter_Settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_draincompliance_label.sizePolicy().hasHeightForWidth())
        self.filter_draincompliance_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.filter_draincompliance_label.setFont(font)
        self.filter_draincompliance_label.setObjectName("filter_draincompliance_label")
        self.horizontalLayout_8.addWidget(self.filter_draincompliance_label)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Wafer_Filter_Settings)
        QtCore.QMetaObject.connectSlotsByName(Wafer_Filter_Settings)

    def retranslateUi(self, Wafer_Filter_Settings):
        _translate = QtCore.QCoreApplication.translate
        Wafer_Filter_Settings.setWindowTitle(_translate("Wafer_Filter_Settings", "Device Parameter Filter"))
        self.wafer_label.setText(_translate("Wafer_Filter_Settings", "Wafer"))
        self.Idmax_min_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having LESS than this maximum |Idmax| will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">|Idmax| is determined from the single-swept transfer curve and is the maximum |drain current| in the Id(Vgs) single swept transfer curve.</span></p></body></html>"))
        self.Idmax_min_label.setText(_translate("Wafer_Filter_Settings", "minimum |Idmax| (A)"))
        self.min_Idmax_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.Idmax_max_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having MORE than this |Idmax| will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">|Idmax| is determined from the single-swept transfer curve and is the maximum |drain current| in the Id(Vgs) single swept transfer curve.</span></p></body></html>"))
        self.Idmax_max_label.setText(_translate("Wafer_Filter_Settings", "maximum |Idmax| (A)"))
        self.max_Idmax_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.IdmaxFOC_min_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having LESS than this maximum |Idmax| will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">|Idmax| is determined from the single-swept transfer curve and is the maximum |drain current| in the Id(Vgs) single swept transfer curve.</span></p></body></html>"))
        self.IdmaxFOC_min_label.setText(_translate("Wafer_Filter_Settings", "minimum |Idmax|FOC"))
        self.min_IdmaxFOC_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.IdmaxFOC_max_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having MORE than this |Idmax| will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">|Idmax| is determined from the single-swept transfer curve and is the maximum |drain current| in the Id(Vgs) single swept transfer curve.</span></p></body></html>"))
        self.IdmaxFOC_max_label.setText(_translate("Wafer_Filter_Settings", "maximum |Idmax|FOC"))
        self.max_IdmaxFOC_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.onoffratio_min_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having LESS than this On-Off Ratio will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">The On-Off Ratio is the ratio of |Idmax|/|Idleak| from the Id(Vgs) single swept transfer curve where |Idleak| is the minimum of |Id(Vgs)|</span></p></body></html>"))
        self.onoffratio_min_label.setText(_translate("Wafer_Filter_Settings", "minimum On-Off Ratio"))
        self.min_onoffratio_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.onoffratio_max_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having MORE than this On-Off Ratio will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">The On-Off Ratio is the ratio of |Idmax|/|Idleak| from the Id(Vgs) single swept transfer curve where |Idleak| is the minimum of |Id(Vgs)|</span></p></body></html>"))
        self.onoffratio_max_label.setText(_translate("Wafer_Filter_Settings", "maximum On-Off Ratio"))
        self.max_onoffratio_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.TLM_Rc_min_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having less than this maximum Gm will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">The maximum Gm is determined from the single-swept transfer curve</span></p></body></html>"))
        self.TLM_Rc_min_label.setText(_translate("Wafer_Filter_Settings", "minimum TLM Rc"))
        self.TLM_Rc_min_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.TLM_Rc_max_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having MORE than this maximum Gm will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">The maximum Gm is determined from the single-swept transfer curve</span></p></body></html>"))
        self.TLM_Rc_max_label.setText(_translate("Wafer_Filter_Settings", "maximum TLM Rc"))
        self.TLM_Rc_max_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.TLM_Rsh_min_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having less than this maximum Gm will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">The maximum Gm is determined from the single-swept transfer curve</span></p></body></html>"))
        self.TLM_Rsh_min_label.setText(_translate("Wafer_Filter_Settings", "minimum TLM Rsh"))
        self.TLM_Rsh_min_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.TLM_Rsh_max_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having MORE than this maximum Gm will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">The maximum Gm is determined from the single-swept transfer curve</span></p></body></html>"))
        self.TLM_Rsh_max_label.setText(_translate("Wafer_Filter_Settings", "maximum TLM Rsh"))
        self.TLM_Rsh_max_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.Ronmin_min_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having LESS than this maximum |Idmax| will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">|Idmax| is determined from the single-swept transfer curve and is the maximum |drain current| in the Id(Vgs) single swept transfer curve.</span></p></body></html>"))
        self.Ronmin_min_label.setText(_translate("Wafer_Filter_Settings", "minimum Ronmin"))
        self.Ronmin_min_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.Igmax_min_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having LESS than this maximum |Idmax| will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">|Idmax| is determined from the single-swept transfer curve and is the maximum |drain current| in the Id(Vgs) single swept transfer curve.</span></p></body></html>"))
        self.Igmax_min_label.setText(_translate("Wafer_Filter_Settings", "minimum |Igmax|"))
        self.Igmax_min_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.Ronmin_max_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having MORE than this |Idmax| will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">|Idmax| is determined from the single-swept transfer curve and is the maximum |drain current| in the Id(Vgs) single swept transfer curve.</span></p></body></html>"))
        self.Ronmin_max_label.setText(_translate("Wafer_Filter_Settings", "maximum Ronmin"))
        self.Ronmin_max_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.Igmax_max_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having LESS than this maximum |Idmax| will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">|Idmax| is determined from the single-swept transfer curve and is the maximum |drain current| in the Id(Vgs) single swept transfer curve.</span></p></body></html>"))
        self.Igmax_max_label.setText(_translate("Wafer_Filter_Settings", "maximum |Igmax|"))
        self.Igmax_max_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.gmmax_min_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having less than this maximum Gm will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">The maximum Gm is determined from the single-swept transfer curve</span></p></body></html>"))
        self.gmmax_min_label.setText(_translate("Wafer_Filter_Settings", "minimum maxgm (S)"))
        self.min_gmmax_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.gmmax_max_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having MORE than this maximum Gm will not be analyzed</span></p><p><span style=\" font-size:12pt; color:#000000;\">The maximum Gm is determined from the single-swept transfer curve</span></p></body></html>"))
        self.gmmax_max_label.setText(_translate("Wafer_Filter_Settings", "maximum maxgm (S)"))
        self.max_gmmax_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.filter_gate_compliance_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.filter_gatecompliance_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having ANY gate current measurements at current compliance will not be analyzed</span></p></body></html>"))
        self.filter_gatecompliance_label.setText(_translate("Wafer_Filter_Settings", "filter gate compliance"))
        self.filter_drain_compliance_but.setText(_translate("Wafer_Filter_Settings", "Off"))
        self.filter_draincompliance_label.setWhatsThis(_translate("Wafer_Filter_Settings", "<html><head/><body><p><span style=\" font-size:12pt; color:#000000;\">This is an analysis criteria i.e. devices having ANY drain current measurements at current compliance will not be analyzed</span></p></body></html>"))
        self.filter_draincompliance_label.setText(_translate("Wafer_Filter_Settings", "filter drain compliance"))

