# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'comparator_widget.ui'
#
# Created: Mon May 15 14:38:03 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Comparator(object):
    def setupUi(self, Comparator):
        Comparator.setObjectName("Comparator")
        Comparator.resize(202, 438)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Comparator)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comparison_type_label = QtWidgets.QLabel(Comparator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comparison_type_label.sizePolicy().hasHeightForWidth())
        self.comparison_type_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comparison_type_label.setFont(font)
        self.comparison_type_label.setAlignment(QtCore.Qt.AlignCenter)
        self.comparison_type_label.setObjectName("comparison_type_label")
        self.verticalLayout_3.addWidget(self.comparison_type_label)
        self.comparison_type_selector = QtWidgets.QComboBox(Comparator)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comparison_type_selector.setFont(font)
        self.comparison_type_selector.setEditable(False)
        self.comparison_type_selector.setObjectName("comparison_type_selector")
        self.verticalLayout_3.addWidget(self.comparison_type_selector)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_prefixA = QtWidgets.QLabel(Comparator)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_prefixA.setFont(font)
        self.label_prefixA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_prefixA.setObjectName("label_prefixA")
        self.verticalLayout.addWidget(self.label_prefixA)
        self.PrefixA = QtWidgets.QComboBox(Comparator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.PrefixA.sizePolicy().hasHeightForWidth())
        self.PrefixA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PrefixA.setFont(font)
        self.PrefixA.setEditable(False)
        self.PrefixA.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.PrefixA.setObjectName("PrefixA")
        self.verticalLayout.addWidget(self.PrefixA)
        self.label_prefixA_data_type = QtWidgets.QLabel(Comparator)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_prefixA_data_type.setFont(font)
        self.label_prefixA_data_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_prefixA_data_type.setObjectName("label_prefixA_data_type")
        self.verticalLayout.addWidget(self.label_prefixA_data_type)
        self.data_type_selectorA = QtWidgets.QComboBox(Comparator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_type_selectorA.sizePolicy().hasHeightForWidth())
        self.data_type_selectorA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.data_type_selectorA.setFont(font)
        self.data_type_selectorA.setEditable(False)
        self.data_type_selectorA.setObjectName("data_type_selectorA")
        self.verticalLayout.addWidget(self.data_type_selectorA)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_prefixB = QtWidgets.QLabel(Comparator)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_prefixB.setFont(font)
        self.label_prefixB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_prefixB.setObjectName("label_prefixB")
        self.verticalLayout_2.addWidget(self.label_prefixB)
        self.PrefixB = QtWidgets.QComboBox(Comparator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PrefixB.sizePolicy().hasHeightForWidth())
        self.PrefixB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.PrefixB.setFont(font)
        self.PrefixB.setEditable(False)
        self.PrefixB.setObjectName("PrefixB")
        self.verticalLayout_2.addWidget(self.PrefixB)
        self.label_prefixB_data_type = QtWidgets.QLabel(Comparator)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_prefixB_data_type.setFont(font)
        self.label_prefixB_data_type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_prefixB_data_type.setObjectName("label_prefixB_data_type")
        self.verticalLayout_2.addWidget(self.label_prefixB_data_type)
        self.data_type_selectorB = QtWidgets.QComboBox(Comparator)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data_type_selectorB.sizePolicy().hasHeightForWidth())
        self.data_type_selectorB.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.data_type_selectorB.setFont(font)
        self.data_type_selectorB.setEditable(False)
        self.data_type_selectorB.setObjectName("data_type_selectorB")
        self.verticalLayout_2.addWidget(self.data_type_selectorB)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.Device_Listing_Table = DevTable(Comparator)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Device_Listing_Table.setFont(font)
        self.Device_Listing_Table.setObjectName("Device_Listing_Table")
        self.Device_Listing_Table.setColumnCount(0)
        self.Device_Listing_Table.setRowCount(0)
        self.verticalLayout_4.addWidget(self.Device_Listing_Table)
        self.paste_data_but = QtWidgets.QPushButton(Comparator)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.paste_data_but.setFont(font)
        self.paste_data_but.setCheckable(False)
        self.paste_data_but.setObjectName("paste_data_but")
        self.verticalLayout_4.addWidget(self.paste_data_but)

        self.retranslateUi(Comparator)
        QtCore.QMetaObject.connectSlotsByName(Comparator)

    def retranslateUi(self, Comparator):
        _translate = QtCore.QCoreApplication.translate
        Comparator.setWindowTitle(_translate("Comparator", "Device to Device Comparator"))
        self.comparison_type_label.setText(_translate("Comparator", "Comparison Type"))
        self.comparison_type_selector.setToolTip(_translate("Comparator", "Selects type of transfer curve"))
        self.comparison_type_selector.setWhatsThis(_translate("Comparator", "Ron @ Vds=0V is the slope of Ids/Vds at Vds=0V\n"
"Ron @ |Vds|=maximum is the maximum Vds/Id at maximum Vds\n"
"Gon s are similar to the above but are conductances = 1/Ron"))
        self.label_prefixA.setText(_translate("Comparator", "Prefix A"))
        self.PrefixA.setToolTip(_translate("Comparator", "Selects type of transfer curve"))
        self.PrefixA.setWhatsThis(_translate("Comparator", "Ron @ Vds=0V is the slope of Ids/Vds at Vds=0V\n"
"Ron @ |Vds|=maximum is the maximum Vds/Id at maximum Vds\n"
"Gon s are similar to the above but are conductances = 1/Ron"))
        self.label_prefixA_data_type.setText(_translate("Comparator", "data type"))
        self.data_type_selectorA.setToolTip(_translate("Comparator", "Selects type of transfer curve"))
        self.data_type_selectorA.setWhatsThis(_translate("Comparator", "Ron @ Vds=0V is the slope of Ids/Vds at Vds=0V\n"
"Ron @ |Vds|=maximum is the maximum Vds/Id at maximum Vds\n"
"Gon s are similar to the above but are conductances = 1/Ron"))
        self.label_prefixB.setText(_translate("Comparator", "Prefix B"))
        self.PrefixB.setToolTip(_translate("Comparator", "Selects type of transfer curve"))
        self.PrefixB.setWhatsThis(_translate("Comparator", "Ron @ Vds=0V is the slope of Ids/Vds at Vds=0V\n"
"Ron @ |Vds|=maximum is the maximum Vds/Id at maximum Vds\n"
"Gon s are similar to the above but are conductances = 1/Ron"))
        self.label_prefixB_data_type.setText(_translate("Comparator", "data type"))
        self.data_type_selectorB.setToolTip(_translate("Comparator", "Selects type of transfer curve"))
        self.data_type_selectorB.setWhatsThis(_translate("Comparator", "Ron @ Vds=0V is the slope of Ids/Vds at Vds=0V\n"
"Ron @ |Vds|=maximum is the maximum Vds/Id at maximum Vds\n"
"Gon s are similar to the above but are conductances = 1/Ron"))
        self.paste_data_but.setText(_translate("Comparator", "Paste Data"))

from devtable import DevTable
